networks:
  expense: {}                 #creating custom bridge network name "expense"
# docker volume create mysql
volumes:
  mysql:
services:
  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: kancharlaajay/mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  # docker run -d --name backend --network expense backend:1.0.0
  backend:
    image: kancharlaajay/backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql
  
  # docker run -d --name frontend --network expense frontend:1.0.0
  frontend:
    image: kancharlaajay/frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
   
